apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc
spec:
  containers:
    - name: pvc-container
      image: busybox
      command: ['sh', '-c', 'sleep 3600']
      volumeMounts:
        - name: volume-pvc
          mountPath: /data
  volumes:
    - name: volume-pvc
      persistentVolumeClaim:
        claimName: my-claim
