apiVersion: v1
kind: Pod
metadata:
  name: pod-4
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

  initContainers:
  - name: mycontainer
    image: busybox
    command: ["sh", "-c", "sleeeeeep 20"]
