apiVersion: v1
kind: Pod
metadata:
  name: pod-3
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      protocol: TCP
      name: http

  initContainers:
  - name: mycontainer
    image: busybox
    command: ["sh", "-c", "sleep 20"]
