apiVersion: v1
kind: Pod
metadata:
  name: pod-2
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      name: nginx-http
      protocol: TCP
  
  - name: tomcat
    image: tomcat
    ports:
    - containerPort: 8080
      name: tomcat-http
      protocol: TCP
