apiVersion: v1
kind: Pod
metadata:
  name: sidecar
  labels:
    type: sidecar
spec:
  containers:
    - name: container1
      image: busybox
      command: ['sh', '-c', 'sleep 3600']
      volumeMounts:
        - name: volume-local
          mountPath: /data

    - name: container2
      image: busybox
      command: ['sh', '-c', 'sleep 3600']
      volumeMounts:
        - name: volume-local
          mountPath: /src

  volumes:
    - name: volume-local
      emptyDir: {}
